### ISSUE TITLE
Unhandled exception when there is no internet connectivity?

### ISSUE THREAD

**Issue by probonopd** [lotun-io/lotun#1]
Unhandled exception when there is no internet connectivity?

```
(node:4) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "authorization"
    at ClientRequest.setHeader (_http_outgoing.js:474:3)
    at new ClientRequest (_http_client.js:184:14)
    at request (https.js:272:10)
    at Object.get (https.js:276:15)
    at WebSocket.initAsClient (/run/firejail/appimage/.appimage-10045/resources/app.asar/node_modules/@lotun/client/node_modules/ws/lib/websocket.js:514:33)
    at new WebSocket (/run/firejail/appimage/.appimage-10045/resources/app.asar/node_modules/@lotun/client/node_modules/ws/lib/websocket.js:62:20)
    at createSocketConnection (/run/firejail/appimage/.appimage-10045/resources/app.asar/node_modules/@lotun/client/lib/socket-client.js:20:14)
    at Object.createConnection (/run/firejail/appimage/.appimage-10045/resources/app.asar/node_modules/@lotun/client/lib/socket-client.js:177:5)
    at LotunClient.connect (/run/firejail/appimage/.appimage-10045/resources/app.asar/node_modules/@lotun/client/lib/api.js:40:18)
    at App.app.on (/run/firejail/appimage/.appimage-10045/resources/app.asar/app/main.js:66:17)
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/952

**Comment by Paulooze** [comment]
Hi @probonopd,

This issue should be fixed in version 0.0.3.

**Comment by Paulooze** [comment]
fixed

**Comment by probonopd** [comment]
Thank you very much @Paulooze. Can you check if you can add the missing `.DirIcon` file please?
